version: '3.8'

services:
  # PostgreSQL Veritabanı
  db:
    image: postgres:14-alpine
    container_name: flax-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: flaxerp
      POSTGRES_USER: flaxuser
      POSTGRES_PASSWORD: ${DB_PASSWORD:-flaxpassword}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"  # Sadece local erişim için
    networks:
      - flax-network

  # Backend (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    container_name: flax-backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:${DB_PASSWORD:-flaxpassword}@db:5432/flaxerp
      - JWT_SECRET=${JWT_SECRET:-flaxsecretkey}
      - HOST=0.0.0.0
    ports:
      - "88.218.130.67:3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - flax-network

  # Frontend (Nuxt.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    container_name: flax-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - API_URL=http://88.218.130.67:3001/api
      - HOST=0.0.0.0
    ports:
      - "88.218.130.67:3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - flax-network

  # Adminer - Veritabanı yönetim aracı (geliştirme aşamasında)
  adminer:
    image: adminer
    container_name: flax-adminer
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"  # Sadece local erişim için, canlıda güvenlik için
    networks:
      - flax-network

networks:
  flax-network:
    driver: bridge

volumes:
  postgres_data:
