version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: flax-erp-postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-flaxerp}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - flax-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flax-erp-backend
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=${DB_USER:-postgres}
      - DATABASE_PASSWORD=${DB_PASSWORD:-postgres}
      - DATABASE_NAME=${DB_NAME:-flaxerp}
      - JWT_SECRET=${JWT_SECRET:-supersecret}
      - NODE_ENV=development
      - HOST=0.0.0.0
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - flax-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: flax-erp-frontend
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:3000
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_FORCE_DISK_CACHE=1
      - NEXT_PUBLIC_IS_DOCKER=true
    ports:
      - "${FRONTEND_PORT:-8080}:3000"
    volumes:
      - ./frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
      - frontend_next_cache:/usr/src/app/.next
    restart: on-failure
    entrypoint: ["sh", "/usr/src/app/entrypoint.sh"]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - flax-network

networks:
  flax-network:
    driver: bridge

volumes:
  postgres_data:
  frontend_node_modules:
  frontend_next_cache:
